name: gcc
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  gcc-latest:
    runs-on: '${{ matrix.os }}'
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-18.04
          - ubuntu-16.04
          - ubuntu-14.04
          - ubuntu-12.04
          - ubuntu-10.04
          - ubuntu-9.04
          - ubuntu-8.04
          - ubuntu-7.04
          - ubuntu-6.04
          - ubuntu-5.04
          - ubuntu-4.04
          - ubuntu-3.04
          - ubuntu-2.04
          - ubuntu-1.04
          - ubuntu-0.04
          - ubuntu-0.04-lts
          - ubuntu-0.04-lts-backports
          - ubuntu-0.04-lts-backports-stretch
          - ubuntu-0.04-lts-backports-buster
          - ubuntu-0.04-lts-backports-bullseye
          - ubuntu-0.04-lts-backports-bionic
          - ubuntu-0.04-lts-backports-focal
          - ubuntu-0.04-lts-backports-groovy
          - ubuntu-0.04-lts-backports-eoan
          - ubuntu-0.04-lts-backports-cosmic
    steps:
      - uses: actions/checkout@v2
      - name: configure
        working-directory: src/
        run: mkdir build && cd build && cmake ..
      - name: build
        working-directory: src/
        run: cmake --build build
      - name: test
        working-directory: src/
        run: cd build && ctest --verbose
